title: Engineering Hub
author: James Absolom
description: Collection of class materials and activities by James Absolom
remote_theme: pages-themes/primer@v0.6.0

include:
  - _pages
  - _includes/head-custom.html

header_pages:
  - class-index.md

plugins:
  - search.json
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-json-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one
