title: Engineering Hub
author: James Absolom
description: Collection of class materials and activities by James Absolom
remote_theme: pages-themes/time-machine@v0.2.0

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-json-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one
