document.addEventListener("DOMContentLoaded", function () {
    const facts = [
        "The Apollo 11 moon landing computer had less processing power than a modern toaster",
        "The Eiffel Tower grows taller in the summer but shrinks in the winter—talk about a seasonal glow-up!",
        "Roller coasters were originally invented to distract people from sinning—thrill-seekers, you’re forgiven!",
        "NASA engineers once fixed a Mars rover by sending a software patch... from Earth, 34 million miles away!",
        "The SR-71 Blackbird leaks fuel while on the ground because it was designed to expand at supersonic speeds",
        "Engineers had to design Japan’s bullet trains with bird-like noses to stop them from making sonic booms",
        "The Golden Gate Bridge’s cables contain enough wire to circle the Earth three times",
        "You can’t open an airplane door mid-flight—cabin pressure makes it impossible unless you’re Hulk",
        "3D printing has been used to make pizza, organs, and even an entire house—engineering meets sci-fi!",
        "The first electric car was built in 1828 — way before Tesla made them cool",
        "Your car’s check engine light could be triggered by a loose gas cap—engineering’s way of trolling you",
        "The first steam engine was built in ancient Greece but was used as a temple toy, not for work",
        "Some modern skyscrapers have pendulums inside them to stop them from swaying too much in the wind",
        "The material used in bulletproof vests (Kevlar) was discovered by accident while looking for better tires",
        "The world’s longest traffic jam lasted 12 days — proof that civil engineers still have work to do",
        "Bridges are designed to ‘breathe’ with temperature changes, expanding and contracting like a giant lung",
        "The first hard drive could store just 5MB of data and was the size of two refrigerators!",
        "LED bulbs can last over 20 years — great for lazy lightbulb changers",
        "The Hoover Dam is strong enough to withstand an 8.0 magnitude earthquake",
        "Water can cut through steel when blasted at ultra-high pressure—it’s basically a Jedi lightsaber",
        "The Mars Rover sings 'Happy Birthday' to itself every year… the loneliest party ever",
        "NASA once spent millions designing a space pen while the Soviets just used a pencil",
        "The Millennium Tower in San Francisco is sinking and leaning—it’s basically a luxury engineering oopsie",
        "A Formula 1 car can drive upside down in a tunnel at high speeds due to insane downforce",
        "Wi-Fi was invented by accident when engineers were researching black holes—thank you, science!",
        "A single wind turbine blade can be longer than a Boeing 747’s wingspan",
        "Bricks in the Great Wall of China were glued together with sticky rice",
        "The world’s first traffic light exploded on its first day—good thing they improved since then!",
        "Airplane windows are oval instead of square to prevent them from cracking under pressure",
        "The Titanic had a fake funnel — it was just for show because aesthetics matter",
        "Early submarines had hand-cranked propellers—talk about leg day for engineers!",
        "Bridges are struck by lightning more often than buildings due to their metal structures",
        "The Large Hadron Collider is the world’s biggest machine, it has a 17 miles circumference! Thats one big doughnut",
        "Your phone’s vibration motor is just a tiny off-center weight spinning super fast",
        "NASA’s Perseverance Rover has a piece of Martian meteorite onboard which fell on earth — taking home soil to Mars!",
        "The Brooklyn Bridge was so over-engineered that it withstood an elephant stampede used to test it",
        "The Empire State Building was originally designed as a mooring station for airships—like a floating airport!",
        "Jet engines can suck in enough air to fill a swimming pool in a second",
        "One of the first recorded ‘engineer’ was Imhotep, who designed the first pyramid around 2600 BC",
        "Velcro was inspired by burrs sticking to a Swiss engineer’s dog — nature is the best engineer",
        "The Saturn V rocket burned fuel so fast that it could drain an Olympic-sized pool in seconds",
        "The London Underground has a secret network of abandoned tunnels that engineers still explore",
        "The world's longest escalator is over 230 meters long — great for lazy engineers",
        "A typical car has about 30,000 parts—losing one tiny bolt could make the whole thing stop working",
        "Toilets on the International Space Station use airflow instead of gravity to flush",
        "NASA’s rovers have their wheels designed with holes that spell out Morse code messages",
        "Your microwave was an accidental invention after an engineer noticed a melted candy bar in his pocket",
        "The longest-running light bulb has been shining for over 120 years — talk about efficiency!",
        "NASA engineers use duct tape for emergency repairs in space because it works on everything",
        "The top of the Burj Khalifa sways up to 2 meters in the wind",
        "NASA once had to rename a space probe part because engineers called it the ‘manhole cover’",
        "A Boeing 747 can fly with just one engine, but pilots really prefer all four",
        "The Mars helicopter, Ingenuity, had to be as light as a tissue because of Mars’ thin atmosphere",
        "The deepest hole ever drilled on Earth is over 12 km deep — scientists had to stop because it got too hot!",
        "Modern elevators have secret ‘nudge’ modes that close the doors faster when they detect someone lingering",
        "The Hubble Space Telescope can see objects over 13 billion light-years away — basically time-traveling",
        "The first programmable computer was built out of gears and punched cards",
        "Your GPS works thanks to Einstein’s relativity theory — otherwise, you’d be lost by several miles",
        "Some car dashboards are designed to look like fighter jet cockpits just to make drivers feel cool",
        "Refrigerators work by removing heat, not adding cold — so technically, they’re just heat thieves",
        "The Golden Gate Bridge is constantly being painted because the sea air eats away at the color",
        "Japan has earthquake-proof skyscrapers that sit on giant rubber shock absorbers",
        "Some modern buildings have algae walls that generate their own power",
        "The Mars Rover had to be redesigned because it originally got stuck in soft sand",
        "The Eiffel Tower has a secret apartment at the top — built just for its engineer",
        "The first robotic vacuum cleaner was invented in 1996, and now we have robot butlers!",
        "Tesla’s autopilot mode has driven over a billion miles — more than some taxi drivers",
        "The first recorded suspension bridge was built by the Incas using woven grass!",
        "NASA once lost a $125 million Mars orbiter because engineers mixed up metric and imperial units",
        "The ISS moves so fast that astronauts see 16 sunrises and sunsets every day",
        "The longest pipeline in the world stretches over 8,000 km — it’s practically a metal snake!",
        "New York’s subway system still has abandoned tunnels engineers use for testing",
        "Some skyscrapers have hollow floors to let the wind pass through and reduce shaking",
        "Ships use sonar to ‘see’ underwater, just like bats use echolocation",
        "The London Eye never stops moving — passengers have to hop on while it’s in motion",
        "NASA’s Perseverance rover has a tiny piece of the Wright brothers’ plane onboard",
        "Modern prosthetic limbs can be controlled by the user’s thoughts — real-life cyborgs!",
        "The world's fastest roller coaster accelerates from 0 to 240 km/h in under 5 seconds!",
        "Hyperloop trains could travel at over 1,000 km/h by eliminating air resistance",
        "NASA’s new spacesuits cost over $200 million each — space fashion is expensive!",
        "Some dams generate power using turbines that can run in reverse when water levels drop",
        "Engineers are working on a ‘space elevator’ that could carry cargo to orbit without rockets",
        "Formula 1 steering wheels have more buttons than a video game controller",
        "The world's largest ship is so big it takes over 3 miles to stop completely",
        "The Space Shuttle’s fuel tank held enough liquid hydrogen to fill 18 Olympic swimming pools!"
    ];
    
    const randomFact = facts[Math.floor(Math.random() * facts.length)];
    
    document.getElementById("fun-fact").innerText = randomFact;
});
