document.addEventListener("DOMContentLoaded", function () {
    const facts = [
        "The Eiffel Tower can be 15 cm taller during the summer due to thermal expansion",
        "Concrete is the most widely used material on Earth after water",
        "NASA's Mars rovers use plutonium as a power source",
        "Bridges are designed to withstand both static and dynamic loads",
        "Ancient Romans used a type of concrete that gets stronger with time",
        "Leonardo da Vinci sketched plans for a helicopter in the 15th century",
        "GPS satellites account for Einstein’s Theory of Relativity to maintain accuracy",
        "Engineers designed Japan's bullet trains to mimic the beak of a kingfisher bird",
        "The London Eye rotates at a speed of 0.26 meters per second",
        "Mechanical engineers designed the first artificial heart",
        "The Golden Gate Bridge’s cables contain over 80,000 miles of wire",
        "The International Space Station orbits Earth at 28,000 km/h",
        "A Boeing 747 consists of about six million parts",
        "3D printing has been used to create entire houses",
        "Hydraulic presses can generate pressures higher than volcanic eruptions",
        "The first recorded engineering textbook was written over 2,000 years ago",
        "Modern skyscrapers can sway up to several meters in strong winds",
        "The first programmable computer was built in the 1940s",
        "Engineers use nanotechnology to make self-cleaning glass",
        "The Panama Canal uses massive locks to lift ships over 26 meters",
        "The Large Hadron Collider is the world’s largest machine",
        "Modern roller coasters can reach speeds of over 240 km/h",
        "The Hoover Dam contains enough concrete to build a highway from coast to coast",
        "Wind turbine blades can be longer than the wingspan of a Boeing 747",
        "Engineers design race car tires to be nearly bald for better grip",
        "Airplane wings are designed to flex rather than remain rigid",
        "The Brooklyn Bridge was the first bridge to use steel-wire cables",
        "Tesla coils can generate lightning-like discharges",
        "The SR-71 Blackbird was so fast that friction heated its surface to 600°F",
        "Solar panels work better in cold temperatures",
        "Modern aircraft use composite materials to reduce weight",
        "Formula 1 cars generate enough downforce to drive upside down",
        "Early elevators were operated manually by attendants",
        "The first successful human flight lasted only 12 seconds",
        "Water can cut through metal using ultra-high-pressure jets",
        "The Apollo 11 spacecraft had less computing power than a smartphone",
        "Wind turbines can produce electricity even in low wind speeds",
        "Engineers use sound waves to detect structural defects in bridges",
        "Hovercrafts can travel over land, water, and ice",
        "The longest railway tunnel in the world is over 57 km long",
        "The world's first floating nuclear power plant is in Russia",
        "Electric cars were more popular than gasoline cars in the early 1900s",
        "Hyperloop technology could revolutionize transportation with speeds over 1,000 km/h",
        "The deepest oil well ever drilled reaches over 12 km underground",
        "LED lights are more efficient than traditional incandescent bulbs",
        "Supersonic jets can travel faster than the speed of sound",
        "Water wheels have been used to generate power for over 2,000 years",
        "The Petronas Towers were the tallest buildings in the world until 2004",
        "Bridges can have expansion joints to allow movement due to temperature changes",
        "The longest suspension bridge spans over 2 km",
        "Engineers designed bionic limbs controlled by the human brain",
        "Some materials can become superconductors at extremely low temperatures",
        "Hydraulic systems are used in aircraft landing gear",
        "The first steam engine was built in the 1st century AD",
        "Fire-resistant glass can withstand temperatures over 1,000°F",
        "Engineers design earthquake-resistant buildings with flexible foundations",
        "The ISS was assembled in space piece by piece",
        "The Hoover Dam produces enough electricity to power 1.3 million homes",
        "The Burj Khalifa is over 800 meters tall",
        "The first transatlantic cable was laid in 1858",
        "Japan's Shinkansen trains use magnetic levitation to reduce friction",
        "Automobile airbags deploy in less than 50 milliseconds",
        "The first water filtration system was created in ancient Egypt",
        "Wind tunnels help engineers test aerodynamics before building prototypes",
        "Concrete can heal itself using bacteria",
        "Spacecraft use gyroscopes for navigation in zero gravity",
        "Airplane black boxes are actually orange for visibility",
        "The Hubble Space Telescope has provided images from over 13 billion light-years away",
        "Smart materials can change shape when exposed to heat or electricity",
        "The world's largest dam is the Three Gorges Dam in China",
        "Deep-sea submersibles can withstand pressures over 1,000 times that of Earth's surface",
        "Engineers use seismic sensors to monitor volcanic activity",
        "Solar roads can generate electricity while supporting vehicle traffic",
        "The world's first commercial jetliner was the de Havilland Comet",
        "Engineers designed the first self-driving car in the 1980s",
        "The tallest wind turbine is over 250 meters tall",
        "High-speed trains use regenerative braking to save energy",
        "Smart grids improve electricity distribution efficiency",
        "Water desalination plants turn seawater into drinkable water",
        "Engineers use AI to optimize factory production lines",
        "Nanorobots may one day repair human cells from within the body",
        "Some aircraft can refuel mid-flight using aerial refueling techniques",
        "The James Webb Space Telescope operates at -233°C",
        "Hyperloop capsules would travel in near-vacuum tunnels to reduce air resistance",
        "Digital twins allow engineers to simulate real-world systems in virtual environments",
        "The first satellite, Sputnik 1, launched in 1957",
        "Airplane fuselages are tested using simulated lightning strikes",
        "Skyscrapers use tuned mass dampers to reduce swaying",
        "Engineers are developing space elevators to transport cargo into orbit",
        "Modern engines can be 50% more efficient than older designs",
        "Underground cables help prevent power outages during storms",
        "Biodegradable plastics are engineered to break down faster",
        "Heat exchangers are used in everything from power plants to refrigerators",
        "The world's deepest metro system is in North Korea",
        "Some dams generate power using reversible turbines",
        "Military aircraft use stealth technology to avoid radar detection",
        "Engineers create self-repairing roads using special asphalt",
        "Magnetorheological fluids change viscosity when exposed to magnetic fields",
        "Quantum computers could revolutionize engineering calculations",
        "Autonomous ships could transform the future of maritime transport"
    ];
    
    const randomFact = facts[Math.floor(Math.random() * facts.length)];
    
    document.getElementById("fun-fact").innerText = randomFact;
});
